In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2], [3, 4]])

In [3]:
A

array([[1, 2],
       [3, 4]])

In [5]:
A

array([[1, 2],
       [3, 4]])

In [7]:
type(A)

numpy.ndarray

In [8]:
A.ndim # 배열의 차원

2

In [10]:
A.shape #배열의 크기

(2, 2)

In [11]:
A.dtype # 원소 자료형

dtype('int32')

In [12]:
print(A.max(), A.mean(), A.min(), A.sum())

4 2.5 1 10


In [13]:
A[0]

array([1, 2])

In [14]:
A[1]

array([3, 4])

In [16]:
A[0][1]

2

In [17]:
A[A>1]

array([2, 3, 4])

In [18]:
# 배열 형태 바꾸기

In [20]:
A.T

array([[1, 3],
       [2, 4]])

In [22]:
A.flatten()

array([1, 2, 3, 4])

In [23]:
#배열의 연산

In [25]:
A+A

array([[2, 4],
       [6, 8]])

In [27]:
A-A

array([[0, 0],
       [0, 0]])

In [29]:
A*A

array([[ 1,  4],
       [ 9, 16]])

In [30]:
A/A

array([[1., 1.],
       [1., 1.]])

In [32]:
# 브로드 캐스팅

In [35]:
B = np.array([10, 100])

A*B

array([[ 10, 200],
       [ 30, 400]])

In [36]:
#내적 구하기
B.dot(B)

10100